name: AutoSignIn
on:
    schedule:
    #UTC时间18点对应北京时间2点
    - cron: '15 16 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-python@v4
        with:
            python-version: 3.9
      - name: Install
        run:
            pip install -r requirements.txt
            playwright install
      - name: Run
        env:
            ACCOUNT: ${{secrets.ACCOUNT}}
        run: |
            python main.py
